# Generated by Django 4.0.4 on 2022-05-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
            ],
        ),
    ]
