# Generated by Django 4.0.4 on 2022-05-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_project_app', '0002_talker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talker',
            old_name='receiver',
            new_name='receiver_email',
        ),
        migrations.RenameField(
            model_name='talker',
            old_name='sender',
            new_name='receiver_name',
        ),
        migrations.AddField(
            model_name='talker',
            name='sender_email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talker',
            name='sender_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
