# Generated by Django 4.0.4 on 2022-05-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_project_app', '0003_rename_receiver_talker_receiver_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.CharField(max_length=100)),
                ('sender_name', models.CharField(max_length=100)),
                ('receiver_email', models.CharField(max_length=100)),
                ('receiver_name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=10000)),
                ('encrypted_img_path', models.CharField(max_length=100)),
            ],
        ),
    ]
