# Generated by Django 4.0.4 on 2022-05-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_project_app', '0004_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='talker',
            name='new_message',
            field=models.BooleanField(default=True),
        ),
    ]
