# Generated by Django 4.0.4 on 2022-05-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_project_app', '0005_talker_new_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='roomcode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talker',
            name='roomcode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='talker',
            name='new_message',
            field=models.BooleanField(default=False),
        ),
    ]
