# Generated by Django 4.0.4 on 2022-05-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_project_app', '0006_messages_roomcode_talker_roomcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talker',
            name='last_message',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
