# Generated by Django 4.0.4 on 2022-05-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_project_app', '0007_talker_last_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encrypted_Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('message_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='encrypted_img_name',
            field=models.CharField(default='nill', max_length=100),
        ),
        migrations.AlterField(
            model_name='messages',
            name='encrypted_img_path',
            field=models.CharField(default='nill', max_length=100),
        ),
    ]
