# Generated by Django 4.0.4 on 2022-05-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_project_app', '0008_encrypted_messages_messages_encrypted_img_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Encrypted_Messages',
        ),
        migrations.AddField(
            model_name='messages',
            name='key',
            field=models.CharField(default='nill', max_length=100),
        ),
    ]
